stages:
  - deploy
variables:
  BACKEND_DIR: /home/projects/pokerapps/mobile-app-backend

deploy_dev:
  stage: deploy
  image: alpine
  before_script:
  - cd
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY_TEMP" | tr -d '\r' > ~/.ssh/ssh_key
  - chmod 600 ~/.ssh/ssh_key
  - ssh-keyscan $NETWORK_TEMP > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  script:
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key "$USER@$NETWORK_TEMP" "
        cd ${BACKEND_DIR}
        git pull origin staging
        docker compose build --no-cache backend &&
        docker compose stop backend &&
        docker compose up -d backend &&
        docker system prune -a -f 
        docker compose logs backend
        "
  only:
    - develop
