stages:
  - deploy

variables:
  BUILD_DIR: /home/projects/pokerapps/mobile-app-backend
  CONTAINER_NAME: backend
deploy_dev:
  stage: deploy
  image: alpine
  before_script:
  - cd
  - 'command -v ssh-agent >/dev/null || ( apk add openssh )'
  - mkdir -p ~/.ssh
  - echo "$SSH_KEY_PRIVATE_TEMP" | tr -d '\r' > ~/.ssh/ssh_key
  - chmod 600 ~/.ssh/ssh_key
  - ssh-keyscan $NETWORK_TEMP > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/ssh_key
  
  script:
  - echo "Connecting to ssh ..."
  - |
    ssh -i ~/.ssh/ssh_key "${USER}@${NETWORK_TEMP}" "
      cd ${BUILD_DIR}
      git pull origin develop && 
      if ! docker compose build --no-cache; then
        echo "Docker build failed ."
        exit 1
      fi
      docker compose stop ${CONTAINER_NAME} || true &&
      docker compose up -d ${SERVICE_NAME} &&
      docker system prune -f -a
    "
  - echo "Back Office successfully deployed."

  only:
    - develop
