version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db    

  # minio:
  #   image: minio/minio:edge
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./VOLUMES/minio:/data
  #   entrypoint: minio server /data
  #   env_file:
  #     - .env
  backend:
    container_name: backend-node-mongo
    restart: always
    image: backend-fullstack
    build: "."
    ports:
      - "4000:4000"
      # - "4000:3003"
    # command: bash -c "while ! curl -s postgres:5432 > /dev/null; do echo waiting for mongodb to be ready ...; sleep 1; pg-god db-create -o postgres -w ${TYPEORM_PASSWORD} -n fullstack || true"
    # entrypoint: bash -c "npm run ${SEED} && npm run ${ENTRYPOINT}"
    # entrypoint: bash -c "npm run start"
    depends_on:
      # - minio
      - mongo
    environment:
      - .env
    external_links:
      - mongo

volumes:
  db:
