version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: adminpassword
    environment:
      - MONGO_INITDB_DATABASE=docker-node-mongo
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=node1234
    # environment:

    volumes:
      - ./mongo-data:/data/db    
  backend:
    container_name: backend-node-mongo
    restart: always
    image: backend-fullstack
    build: "."
    ports:
      - "4000:4000"
      # - "4000:3003"
    # command: bash -c "while ! curl -s postgres:5432 > /dev/null; do echo waiting for mongodb to be ready ...; sleep 1; pg-god db-create -o postgres -w ${TYPEORM_PASSWORD} -n fullstack || true"
    # entrypoint: bash -c "npm run ${SEED} && npm run ${ENTRYPOINT}"
    # entrypoint: bash -c "npm run start"
    depends_on:
      # - minio
      - mongo
    environment:
      - .env
    external_links:
      - mongo

volumes:
  db:
