services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '127.0.0.1:27017:27017'
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: adminpassword
    environment:
      - MONGO_INITDB_DATABASE=docker-node-mongo
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=node1234
    # environment:

    volumes:
      - ./mongo-data:/data/db    
  backend:
    container_name: backend-node-mongo
    restart: always
    image: backend-fullstack
    build: "."
    ports:
      - "4000:4000"
    depends_on:
      # - minio
      - mongo
    env_file:
      - .env
    external_links:
      - mongo

volumes:
  db:
