  declare interface NotificationRequestDTO { }
  declare interface NotificationResponseDTO { }
  declare interface UtilisateurRequestDTO { }
  declare interface UtilisateurResponseDTO { }
  declare interface LangueRequestDTO { }
  declare interface LangueResponseDTO { }
  declare interface CountryRequestDTO { }
  declare interface CountryResponseDTO { }
  declare interface SignInRequestDTO { }
  declare interface SignInResponseDTO { }
  declare interface SocialNetworkRequestDTO { }
  declare interface SocialNetworkResponseDTO { }
  declare interface BaseInformationRequestDTO { }
  declare interface BaseInformationResponseDTO { }
  declare interface ProfileRequestDTO { }
  declare interface ProfileResponseDTO { }
  declare interface SponsorRequestDTO { }
  declare interface SponsorResponseDTO { }
  declare interface PartenerRequestDTO { }
  declare interface PartenerResponseDTO { }
  declare interface LinkRequestDTO { }
  declare interface LinkResponseDTO { }
  declare interface PageRequestDTO { }
  declare interface PageResponseDTO { }
  declare interface PageAdditionalRequestDTO { }
  declare interface PageAdditionalResponseDTO { }
  declare interface PseudoRequestDTO { }
  declare interface PseudoResponseDTO { }
  declare interface RoleRequestDTO { }
  declare interface RoleResponseDTO { }
  declare interface PaysRequestDTO { }
  declare interface PaysResponseDTO { }
  declare interface ComplementaryInformationRequestDTO { }
  declare interface ComplementaryInformationResponseDTO { }
  declare interface ClubRequestDTO { }
  declare interface ClubResponseDTO { }
  declare interface EventRequestDTO { }
  declare interface EventResponseDTO { }
  declare interface LocationRequestDTO { }
  declare interface LocationResponseDTO { }
  declare interface ConfindialityRequestDTO { }
  declare interface ConfindialityResponseDTO { }
  declare interface CommentRequestDTO { }
  declare interface CommentResponseDTO { }
  declare interface GameTypeRequestDTO { }
  declare interface GameTypeResponseDTO { }
  declare interface TournamentTypeRequestDTO { }
  declare interface TournamentTypeResponseDTO { }
  declare interface PublicationRequestDTO { }
  declare interface PublicationResponseDTO { }
  declare interface UserCredentialRequestDTO { }
  declare interface UserCredentialResponseDTO { }
  declare interface PaymentTypeRequestDTO { }
  declare interface PaymentTypeResponseDTO { }
  declare interface UserSubscriptionRequestDTO { }
  declare interface UserSubscriptionResponseDTO { }
  declare interface SubscriptionOfferRequestDTO { }
  declare interface SubscriptionOfferResponseDTO { }
  declare interface SubscriptionHistoryRequestDTO { }
  declare interface SubscriptionHistoryResponseDTO { }
  declare interface LevelRequestDTO { }
  declare interface LevelResponseDTO { }
  declare interface IdentityVerificationRequestDTO { }
  declare interface IdentityVerificationResponseDTO { }
  declare interface CodeParrainRequestDTO { }
  declare interface CodeParrainResponseDTO { }
  declare interface DayRequestDTO { }
  declare interface DayResponseDTO { }
  declare interface ParticipateRequestDTO { }
  declare interface ParticipateResponseDTO { }
  declare interface PhoneRequestDTO { }
  declare interface PhoneResponseDTO { }
  declare interface SessionRequestDTO { }
  declare interface SessionResponseDTO { }
  declare interface BankRollRequestDTO { }
  declare interface BankRollResponseDTO { }
  declare interface DeviceRequestDTO { }
  declare interface DeviceResponseDTO { }
  declare interface NoteRequestDTO { }
  declare interface NoteResponseDTO { }
  declare interface AvisRequestDTO { }
  declare interface AvisResponseDTO { }
  declare interface MessageRequestDTO { }
  declare interface MessageResponseDTO { }
  declare interface FollowersRequestDTO { }
  declare interface FollowersResponseDTO { }
  declare interface GaugeRequestDTO { }
  declare interface GaugeResponseDTO { }
  declare interface StrategyRequestDTO { }
  declare interface StrategyResponseDTO { }
  declare interface NoteValueRequestDTO { }
  declare interface NoteValueResponseDTO { }
  declare interface NoticedRequestDTO { }
  declare interface NoticedResponseDTO { }
  declare interface PartenariatRequestDTO { }
  declare interface PartenariatResponseDTO { }
  declare interface CurrencyRequestDTO { }
  declare interface CurrencyResponseDTO { }
  declare interface TwoFactorAuthenticationRequestDTO { }
  declare interface TwoFactorAuthenticationResponseDTO { }
  declare interface AlbumRequestDTO { }
  declare interface AlbumResponseDTO { }
  declare interface MediasRequestDTO { }
  declare interface MediasResponseDTO { }
  declare interface DonationRequestDTO { }
  declare interface DonationResponseDTO { }
  declare interface RegistrationRequestDTO { }
  declare interface RegistrationResponseDTO { }
  declare interface SettingsRequestDTO { }
  declare interface SettingsResponseDTO { }
  declare interface ReportRequestDTO { }
  declare interface ReportResponseDTO { }
  declare interface VisitorsRequestDTO { }
  declare interface VisitorsResponseDTO { }
