  declare interface MessageRequestDTO { }
  declare interface MessageResponseDTO { }
  declare interface NotificationRequestDTO { }
  declare interface NotificationResponseDTO { }
  declare interface ParrainageRequestDTO { }
  declare interface ParrainageResponseDTO { }
  declare interface UtilisateurRequestDTO { }
  declare interface UtilisateurResponseDTO { }
  declare interface LangueRequestDTO { }
  declare interface LangueResponseDTO { }
  declare interface CountryRequestDTO { }
  declare interface CountryResponseDTO { }
  declare interface SignInRequestDTO { }
  declare interface SignInResponseDTO { }
  declare interface SocialMediaRequestDTO { }
  declare interface SocialMediaResponseDTO { }
  declare interface BaseInformationRequestDTO { }
  declare interface BaseInformationResponseDTO { }
  declare interface ProfileRequestDTO { }
  declare interface ProfileResponseDTO { }
  declare interface SponsorRequestDTO { }
  declare interface SponsorResponseDTO { }
  declare interface PartenerRequestDTO { }
  declare interface PartenerResponseDTO { }
  declare interface LinksRequestDTO { }
  declare interface LinksResponseDTO { }
  declare interface CasinoProfileRequestDTO { }
  declare interface CasinoProfileResponseDTO { }
  declare interface CasinoProfileAdditionalRequestDTO { }
  declare interface CasinoProfileAdditionalResponseDTO { }
  declare interface PseudoRequestDTO { }
  declare interface PseudoResponseDTO { }
  declare interface RoleRequestDTO { }
  declare interface RoleResponseDTO { }
  declare interface PaysRequestDTO { }
  declare interface PaysResponseDTO { }
  declare interface ComplementaryInformationRequestDTO { }
  declare interface ComplementaryInformationResponseDTO { }
  declare interface ClubRequestDTO { }
  declare interface ClubResponseDTO { }
  declare interface PrivateEventRequestDTO { }
  declare interface PrivateEventResponseDTO { }
  declare interface LocationRequestDTO { }
  declare interface LocationResponseDTO { }
  declare interface ConfindialityRequestDTO { }
  declare interface ConfindialityResponseDTO { }
  declare interface CommentRequestDTO { }
  declare interface CommentResponseDTO { }
